services:
  traffic-tester:
    image: traffic-tester:latest
    container_name: traffic-tester
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    entrypoint: ["/app/traffic-tester-exec"]
